openapi: 3.0.2
  Access-Control-Allow-Origin:*
info:
  description: "API для работы с админ панелью"
  version: "3.0.0"
  title: "Admin API"

servers:
  - url: http://localhost/

paths:
  /user:
    patch:
      summary: 'Изменение настроек пользователя по Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: "Возвращает сохраненного пользователя и статус успешности сохранения"
  /login:
    post:
      summary: 'Авторизация пользователя'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
      responses:
        '200':
          description: "Возвращает сохраненного пользователя и статус успешности сохранения"


components:
  schemas:
    Auth:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          example: '123'
        password:
          description: 'Логин'
          type: string
          example: '123123123'
    User:
      type: object
      required:
        - id
        - login
      properties:
        id:
          type: integer
          example: 12
        login:
          description: 'Логин'
          type: string
          example: 'Ivan'
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
